### ISSUE TITLE
Demote headlines to level 3

### ISSUE THREAD

**Issue by i-like-robots** [Financial-Times/n-teaser#37]
I think most use-cases see the cards at the third-level in the document outline, beneath the page title and a sub-section heading, E.G.

H1. Financial Times Home Page -> H2. Top Stories -> *teaser*
H1. Stream name -> H2. Latest in stream name -> *teaser*
H1. Article headline -> H2. Related Stories -> *teaser*

The only place I can see that this not currently the case is on non-curated stream pages.

**Comment by onishiweb** [comment]
There's no heading level specified by `o-teaser` the styling should work on any element. Is this just something you'd like to see fixed in the demos to prevent people copy/pasting the wrong levels or is this an implementation you've seen somewhere that needs fixing?

**Comment by i-like-robots** [comment]
Next apps are using the templates provided by this component, here:
https://github.com/Financial-Times/n-teaser/blob/master/templates/partials/heading.html

I anticipate the next app use-cases are similar to other products that will implement o-teaser, so maybe the demos there could reflect this also?

**Comment by onishiweb** [comment]
Yep sure. Also sorry I misread this repo as `o-teaser` instead of `n-teaser`. But yeh I'll reflect that in `o-teaser` when I next get chance.

**Comment by i-like-robots** [comment]
I thought you might have!
